### PR TITLE
Fix Travis CI build issues #2128

### LINKED ISSUE #2128: Fix Travis
Travis is currently failing. Please help to fix it.

### PR DESCRIPTION
**Pull request by pranavkarthik10**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [ ] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Before this PR, the travis builds were not working as expected, thus not updating the heroku deployment on each merged PR or commit. Now it works as expected.

#### Changes proposed in this pull request:

- Update deprecated istanbul package to nyc
- Add new scripts to package.json
- Install g++ before install so serverTest.js works
- Temporarily disable npm test which was unncessarily causing errors

Fixes #2128

### CODE REVIEW

**Comment by pranavkarthik10** [comment]
@mariobehling Please take a look at this. You can view the succeeded build logs https://travis-ci.org/fossasia/open-event-wsgen/builds/635582280.

**Comment by pranavkarthik10** [comment]
@mariobehling @aayusharora Please review and merge. Thanks!

**Comment by Sid911** [comment]
travis has been running for more than 13 hours now 😕

**Comment by pranavkarthik10** [comment]
Thank you!

**Pull request merged**
