### PR TITLE
Updated outdated dependencies

### LINKED ISSUE #2168: Update outdated dependencies
The dependencies for this repository are out of date. Please check the list here: https://david-dm.org/fossasia/open-event-wsgen

Update the dependencies.

### PR DESCRIPTION
**Pull request by Dishebh**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Updated some outdated dependencies of the project.

Fixes #2168

### CODE REVIEW

**Comment by kushthedude** [comment]
Wrong way, Please update it

**Comment by Dishebh** [comment]
@kushthedude Shall I try adding the dependabot to the project repo?

**Comment by mariobehling** [comment]
@Dishebh Yes, please go ahead.

**Comment by Dishebh** [comment]
> @Dishebh Yes, please go ahead.

Requested access to the repo for dependabot-preview. Pls grant access.

**Comment by kushthedude** [comment]
@iamareebjamal This can be closed now!

**Pull request closed without merging**
