### PR TITLE
issue 2322 removed

### PR DESCRIPTION
**Pull request by b2pacific**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Changes proposed in this pull request:

-
-
-

Fixes #

### CODE REVIEW

**Review by Raunaksingh100 — COMMENTED** [review]
plz added the issue number and fixed the travis failed in your pr

**Comment by b2pacific** [comment]
I am getting the travis error because of invalid AWS access key

**Comment by iamareebjamal** [comment]
Please fill PR title and description properly. Look at any merged PR

**Comment by iamareebjamal** [comment]
This issue has been fixed already

**Pull request closed without merging**
