### PR TITLE
Fixed the sessions page

### LINKED ISSUE #2137: Schedule page sessions width and area not same as on tracks.html
Please ensure the sessions page are the same as the tracks.html page, e.g. make it full width using the area available.

Compare schedule page;
screenshot from 2019-02-18 01-58-58

to tracks page. It should look the same!
screenshot from 2019-02-18 01-58-34

### PR DESCRIPTION
**Pull request by Dishebh**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Made the sessions page same as the tracks page.

Fixes #2137 

#### Screenshot of the result:
Screenshot from 2020-01-05 17-02-33

### CODE REVIEW

**Comment by Dishebh** [comment]
@mariobehling Pls have a look at the above PR, see if it solves the issue?

**Comment by mariobehling** [comment]
Thanks. Seems like it solves it. Please provide a test page.

**Comment by Dishebh** [comment]
Here's the test link:
https://dishebh.github.io/2019.fossasia.org/event/schedule

Thanks

**Comment by iamareebjamal** [comment]
This broke these tests:

https://github.com/fossasia/open-event-wsgen/blob/c89beec0ad9d92528c508b69ccdcc3a1b37707d7/test/generatorAndSchedule.js#L371-L390

And completely broke the layout of tracks

**Comment by Dishebh** [comment]
> This broke these tests:
> 
> https://github.com/fossasia/open-event-wsgen/blob/c89beec0ad9d92528c508b69ccdcc3a1b37707d7/test/generatorAndSchedule.js#L371-L390
> 
> And completely broke the layout of tracks

Can you please suggest the necessary changes need yo be done to pass the tests?

**Comment by Dishebh** [comment]
> > This broke these tests:
> > https://github.com/fossasia/open-event-wsgen/blob/c89beec0ad9d92528c508b69ccdcc3a1b37707d7/test/generatorAndSchedule.js#L371-L390
> > 
> > And completely broke the layout of tracks
> 
> Can you please suggest the necessary changes need to be done to pass the tests?

**Pull request merged**
