### PR TITLE
Fixed the positioning of navbar

### LINKED ISSUE #2155: Navbar isn't fixed at top
**Actual Behaviour**

Nav menu doesn't remain fixed at top, while scrolling
**Expected Behaviour**

Navbar should be fixed
**Steps to reproduce it**

- Go to the [website](http://scged.eventyay.com)
- You'll see the navbar doesn't remain fixed

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Dishebh**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fixed the navbar at top while scrolling

Fixes #2155

### CODE REVIEW

**Comment by Dishebh** [comment]
@mariobehling pls have a look at the above PR, see if it solves the issue?

**Comment by mariobehling** [comment]
Please provide test page and test deployment of generator.

**Comment by Dishebh** [comment]
Here's the test link:
https://dishebh.github.io/open-event-wsgen/
Thanks!

**Comment by mariobehling** [comment]
GH-Pages are automatically created when a PR in the dev or master branch is made. This PR is therefore not targeting the root of issues. Closing it.

**Pull request closed without merging**
