### PR TITLE
Fixed redirect urls of nav items

### LINKED ISSUE #2153: Nav links not working
**Actual Behaviour**

The links in the navbar doesn't respond anything.
 
**Expected Behaviour**

The redirect links should be fixed with correct redirect urls

**Steps to reproduce it**

- Go to the [website](http://sched.eventyay.com/)
- Click on the nav links above.

**Screenshots of the issue**

Screenshot from 2020-01-05 14-03-11

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Dishebh**
#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia).
- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added necessary documentation (if appropriate)

#### Short description of what this resolves:
Fixed the redirect urls of nav components

Fixes #2153

### CODE REVIEW

**Comment by Dishebh** [comment]
@mariobehling pls have a look at the above PR, see if it solves the issue?

**Comment by mariobehling** [comment]
> @mariobehling pls have a look at the above PR, see if it solves the issue?

Please avoid this message in each single of your PRs. People are getting messages anyways. You can ping on the channel for reviews. Please engage other developers to review and follow best practices, which means provide a test page and test deployment for each change. Thanks!

**Comment by Dishebh** [comment]
> > @mariobehling pls have a look at the above PR, see if it solves the issue?
> 
> Please avoid this message in each single of your PRs. People are getting messages anyways. You can ping on the channel for reviews. Please engage other developers to review and follow best practices, which means provide a test page and test deployment for each change. Thanks!

Thanks a lot for referring and sorry for the issue caused. I know it can be a bit pestering sometimes, I just realised it now. I will keep the best practices in mind from now. Thanks!

P.S I will share the test link asap

**Comment by Dishebh** [comment]
> > @mariobehling pls have a look at the above PR, see if it solves the issue?
> 
> Please avoid this message in each single of your PRs. People are getting messages anyways. You can ping on the channel for reviews. Please engage other developers to review and follow best practices, which means provide a test page and test deployment for each change. Thanks!

Here's the test link:
https://dishebh.github.io/open-event-wsgen/
Thanks!

**Comment by mariobehling** [comment]
GH-Pages are automatically created when a PR in the dev or master branch is made. This PR is therefore not targeting the root of issues. Closing it.

**Pull request closed without merging**
